<a href="https://colab.research.google.com/github/vinodhinialaguraj/linear-regression/blob/main/DTC_ipyn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
iris = load_iris()

iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)

iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
X, y = iris.data, iris.target

print(X.shape, y.shape)

(150, 4) (150,)


In [ ]:
print(np.unique(y))
print(iris.target_names)

[0 1 2]
['setosa' 'versicolor' 'virginica']


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.2, 
                                                    stratify=y, 
                                                    random_state=42)

In [ ]:
std_scaler = StandardScaler()

std_scaler = std_scaler.fit(X_train)

X_train_std = std_scaler.transform(X_train)
X_test_std = std_scaler.transform(X_test)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
dtc= DecisionTreeClassifier().fit(X_train,y_train)
scores=cross_val_score(dtc,X_train_std,y_train,cv=5)
print(scores)
print(scores.mean())

[0.91666667 0.95833333 0.95833333 0.91666667 0.91666667]
0.9333333333333333


In [ ]:
y_pred_dtc=dtc.predict(X_test)
print(y_pred_dtc)

[0 2 1 1 0 1 0 0 2 1 2 2 2 1 0 0 0 1 1 2 0 2 1 2 2 2 1 0 2 0]


In [ ]:
from sklearn import metrics  
print('Mean Absolute Error:', 
      metrics.mean_absolute_error(y_test, y_pred_dtc)) 

Mean Absolute Error: 0.03333333333333333
